// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Metric.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from Metric.proto</summary>
public static partial class MetricReflection {

  #region Descriptor
  /// <summary>File descriptor for Metric.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static MetricReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CgxNZXRyaWMucHJvdG8aH2dvb2dsZS9wcm90b2J1Zi90aW1lc3RhbXAucHJv",
          "dG8iRgoLTWV0cmljVmFsdWUSKAoEZGF0ZRgBIAEoCzIaLmdvb2dsZS5wcm90",
          "b2J1Zi5UaW1lc3RhbXASDQoFdmFsdWUYAiABKAEiXwoGTWV0cmljEgwKBG5h",
          "bWUYASABKAkSEgoKdW5pdF92YWx1ZRgCIAEoCRIbCgV2YWx1ZRgDIAMoCzIM",
          "Lk1ldHJpY1ZhbHVlEhYKDmxlc3NfaXNfYmV0dGVyGAQgASgIYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::MetricValue), global::MetricValue.Parser, new[]{ "Date", "Value" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Metric), global::Metric.Parser, new[]{ "Name", "UnitValue", "Value", "LessIsBetter" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class MetricValue : pb::IMessage<MetricValue>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<MetricValue> _parser = new pb::MessageParser<MetricValue>(() => new MetricValue());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<MetricValue> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::MetricReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public MetricValue() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public MetricValue(MetricValue other) : this() {
    date_ = other.date_ != null ? other.date_.Clone() : null;
    value_ = other.value_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public MetricValue Clone() {
    return new MetricValue(this);
  }

  /// <summary>Field number for the "date" field.</summary>
  public const int DateFieldNumber = 1;
  private global::Google.Protobuf.WellKnownTypes.Timestamp date_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::Google.Protobuf.WellKnownTypes.Timestamp Date {
    get { return date_; }
    set {
      date_ = value;
    }
  }

  /// <summary>Field number for the "value" field.</summary>
  public const int ValueFieldNumber = 2;
  private double value_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public double Value {
    get { return value_; }
    set {
      value_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as MetricValue);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(MetricValue other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(Date, other.Date)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Value, other.Value)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (date_ != null) hash ^= Date.GetHashCode();
    if (Value != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Value);
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (date_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(Date);
    }
    if (Value != 0D) {
      output.WriteRawTag(17);
      output.WriteDouble(Value);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (date_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(Date);
    }
    if (Value != 0D) {
      output.WriteRawTag(17);
      output.WriteDouble(Value);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (date_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Date);
    }
    if (Value != 0D) {
      size += 1 + 8;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(MetricValue other) {
    if (other == null) {
      return;
    }
    if (other.date_ != null) {
      if (date_ == null) {
        Date = new global::Google.Protobuf.WellKnownTypes.Timestamp();
      }
      Date.MergeFrom(other.Date);
    }
    if (other.Value != 0D) {
      Value = other.Value;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (date_ == null) {
            Date = new global::Google.Protobuf.WellKnownTypes.Timestamp();
          }
          input.ReadMessage(Date);
          break;
        }
        case 17: {
          Value = input.ReadDouble();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          if (date_ == null) {
            Date = new global::Google.Protobuf.WellKnownTypes.Timestamp();
          }
          input.ReadMessage(Date);
          break;
        }
        case 17: {
          Value = input.ReadDouble();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class Metric : pb::IMessage<Metric>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Metric> _parser = new pb::MessageParser<Metric>(() => new Metric());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<Metric> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::MetricReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Metric() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Metric(Metric other) : this() {
    name_ = other.name_;
    unitValue_ = other.unitValue_;
    value_ = other.value_.Clone();
    lessIsBetter_ = other.lessIsBetter_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Metric Clone() {
    return new Metric(this);
  }

  /// <summary>Field number for the "name" field.</summary>
  public const int NameFieldNumber = 1;
  private string name_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Name {
    get { return name_; }
    set {
      name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "unit_value" field.</summary>
  public const int UnitValueFieldNumber = 2;
  private string unitValue_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string UnitValue {
    get { return unitValue_; }
    set {
      unitValue_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "value" field.</summary>
  public const int ValueFieldNumber = 3;
  private static readonly pb::FieldCodec<global::MetricValue> _repeated_value_codec
      = pb::FieldCodec.ForMessage(26, global::MetricValue.Parser);
  private readonly pbc::RepeatedField<global::MetricValue> value_ = new pbc::RepeatedField<global::MetricValue>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<global::MetricValue> Value {
    get { return value_; }
  }

  /// <summary>Field number for the "less_is_better" field.</summary>
  public const int LessIsBetterFieldNumber = 4;
  private bool lessIsBetter_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool LessIsBetter {
    get { return lessIsBetter_; }
    set {
      lessIsBetter_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as Metric);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(Metric other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Name != other.Name) return false;
    if (UnitValue != other.UnitValue) return false;
    if(!value_.Equals(other.value_)) return false;
    if (LessIsBetter != other.LessIsBetter) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Name.Length != 0) hash ^= Name.GetHashCode();
    if (UnitValue.Length != 0) hash ^= UnitValue.GetHashCode();
    hash ^= value_.GetHashCode();
    if (LessIsBetter != false) hash ^= LessIsBetter.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Name.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Name);
    }
    if (UnitValue.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(UnitValue);
    }
    value_.WriteTo(output, _repeated_value_codec);
    if (LessIsBetter != false) {
      output.WriteRawTag(32);
      output.WriteBool(LessIsBetter);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Name.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Name);
    }
    if (UnitValue.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(UnitValue);
    }
    value_.WriteTo(ref output, _repeated_value_codec);
    if (LessIsBetter != false) {
      output.WriteRawTag(32);
      output.WriteBool(LessIsBetter);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Name.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
    }
    if (UnitValue.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(UnitValue);
    }
    size += value_.CalculateSize(_repeated_value_codec);
    if (LessIsBetter != false) {
      size += 1 + 1;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(Metric other) {
    if (other == null) {
      return;
    }
    if (other.Name.Length != 0) {
      Name = other.Name;
    }
    if (other.UnitValue.Length != 0) {
      UnitValue = other.UnitValue;
    }
    value_.Add(other.value_);
    if (other.LessIsBetter != false) {
      LessIsBetter = other.LessIsBetter;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Name = input.ReadString();
          break;
        }
        case 18: {
          UnitValue = input.ReadString();
          break;
        }
        case 26: {
          value_.AddEntriesFrom(input, _repeated_value_codec);
          break;
        }
        case 32: {
          LessIsBetter = input.ReadBool();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          Name = input.ReadString();
          break;
        }
        case 18: {
          UnitValue = input.ReadString();
          break;
        }
        case 26: {
          value_.AddEntriesFrom(ref input, _repeated_value_codec);
          break;
        }
        case 32: {
          LessIsBetter = input.ReadBool();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
